name: Build RTL8723BE Kext

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-driver:
    runs-on: macos-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 2. Agora o robô entra primeiro em linux e depois em rtl8723be
      - name: Compilar Kext
        run: |
          cd linux/rtl8723be
          make

      # 3. Atualizado o caminho do upload também
      - name: Upload do Artefato (Kext)
        uses: actions/upload-artifact@v4
        with:
          name: RTL8723BE_MacDriver_Kext
          path: linux/rtl8723be/RTL8723BE_MacDriver.kext
